from PyUtilities.Config import Config

cfg = Config("mygan",
        # data detail
        job_name = "mygan_macpro_20114",
        folder_name = "Delphes",
        input_csv_path = "/Users/lucien/Downloads/input_new.csv",
        preprocess_df_path = "/Users/lucien/Downloads/input_new_cleaned.csv",
        output_path = "output/mygan_macpro_20114/",
        #drop_column_list = [3,4,5,6,7,8,9,10,11,12,13,],
        drop_column_list = [4,],
        drop_condition_column_list = [4,5,6,],
        
        # training detail
        n_event = 1000000,
        n_epoch = 200000,
        batch_size = 512,
        save_per_point = 100,
        print_per_point = 100,
        disc_model_name = "disc_model.h5",
        gen_model_name = "gen_model.h5",
        use_gpu_verbose = False,
       
        ndf = 9,
        latent_dim = 8,
        disc_learning_rate=5E-4,
        disc_beta_1=0.5, 
        disc_beta_2=0.99, 
        disc_epsilon = 1E-9,
        gen_learning_rate=1E-3, 
        gen_beta_1=0.5, 
        gen_beta_2=0.99, 
        gen_epsilon = 1E-9,
        disc_neuron_list = [64,128,256,256,128,64,8,],
        gen_neuron_list = [64,128,256,512,256,128,],
        condition_input_shape = (4,),
        n_real_disc_epoch = 1,
        n_fake_disc_epoch = 1,
        
        plot_folder_name = "plot_optimise_mygan",
        plot_size = 20000,
        plot_per_point = 100,
        plot_bins = 50,
        plot_range = [-3.,3.],
        plot_select_conditions = [
            Config("pt0-20_barrel_phi",min_pt=0.,max_pt=0.2,min_eta=0.,max_eta=1.4,),
            Config("pt20-40_barrel_phi",min_pt=0.2,max_pt=0.4,min_eta=0.,max_eta=1.4,),
            Config("pt40-60_barrel_phi",min_pt=0.4,max_pt=0.6,min_eta=0.,max_eta=1.4,),
            Config("pt60-80_barrel_phi",min_pt=0.6,max_pt=0.8,min_eta=0.,max_eta=1.4,),
            Config("pt80-100_barrel_phi",min_pt=0.8,max_pt=1.0,min_eta=0.,max_eta=1.4,),
            Config("pt100-Inf_barrel_phi",min_pt=1.0,max_pt=99999.,min_eta=0.,max_eta=1.4,),
            Config("pt0-20_endcap_phi",min_pt=0.,max_pt=0.2,min_eta=1.4,max_eta=2.5,),
            Config("pt20-40_endcap_phi",min_pt=0.2,max_pt=0.4,min_eta=1.4,max_eta=2.5,),
            Config("pt40-60_endcap_phi",min_pt=0.4,max_pt=0.6,min_eta=1.4,max_eta=2.5,),
            Config("pt60-80_endcap_phi",min_pt=0.6,max_pt=0.8,min_eta=1.4,max_eta=2.5,),
            Config("pt80-100_endcap_phi",min_pt=0.8,max_pt=1.0,min_eta=1.4,max_eta=2.5,),
            Config("pt100-Inf_endcap_phi",min_pt=1.0,max_pt=99999.,min_eta=1.4,max_eta=2.5,),
        ],
        var_list = [
            Config("Pt",range=(0.,2.),index=0,),
            Config("Eta",range=(-3.,3.),index=1),
            Config("Phi",range=(-3.,3.),index=2),
            Config("TOF",range=(-1.,1.),index=3,mean_index=0,),
            Config("D0",range=(-1.,1.),index=4,mean_index=2,),
            Config("DZ",range=(-2.,2.),index=5,mean_index=4,),
            Config("Outerx",range=(-1.,1.),index=6,mean_index=6,),
            Config("Outery",range=(-1.,1.),index=7,mean_index=8,),
            Config("Outerz",range=(-1.,1.),index=8,mean_index=10,),
            ],
        log_output_path = "",

        trained_generator_path = "/cmsuf/data/store/user/t2/users/klo/HEP-ML-Tools/Delphes/mygan_slurm_20200827_v1/gen_model_25700.h5", 
        )
